image: gitpod/workspace-python:2023-04-18-14-35-39
tasks:
  - command: |
      # Confirm the current shallow clone
      git log -n 5

      # Attempt to deepen
      git fetch --deepen=5

      # Verify the operation
      git log -n 5

